"""
Tidal boundary condition module — placeholder template.

Replace this file with the output of `prepare_bc.py` which extracts
real tidal harmonics from FES2014 or TPXO9. This template provides
a synthetic M2-only tide for testing.

To use real data:
    python scripts/prepare_bc.py \
        --mesh input/mesh_philippines.msh \
        --fes2014-dir /path/to/fes2014 \
        --output input/tidal_forcing.py

Or with TPXO9:
    python scripts/prepare_bc.py \
        --mesh input/mesh_philippines.msh \
        --tpxo /path/to/tpxo9.nc \
        --output input/tidal_forcing.py
"""

import numpy as np

# --- Tidal constituent data ---
# Generated by prepare_bc.py.
# Each constituent has: amp (m), phase_deg (°), omega (rad/s)
CONSTITUENTS = {
    "M2": {
        "amp": [0.52],
        "phase_deg": [120.0],
        "omega": 1.405189e-04,
    },
    "S2": {
        "amp": [0.23],
        "phase_deg": [145.0],
        "omega": 1.454441e-04,
    },
    "K1": {
        "amp": [0.31],
        "phase_deg": [210.0],
        "omega": 7.292116e-05,
    },
    "O1": {
        "amp": [0.25],
        "phase_deg": [195.0],
        "omega": 6.759774e-05,
    },
}


def tidal_elevation(x, y, t):
    """
    Compute tidal water elevation (m) at spatial coordinates and time.

    Args:
        x, y: Spatial coordinates (lon, lat) at boundary nodes
        t: Time in seconds since simulation start
    Returns:
        Water elevation in meters
    """
    eta = 0.0
    for name, data in CONSTITUENTS.items():
        amp = np.mean(data["amp"])
        phase_rad = np.deg2rad(np.mean(data["phase_deg"]))
        omega = data["omega"]
        eta += amp * np.cos(omega * t - phase_rad)
    return eta
