#!/usr/bin/env python3
"""Capture screenshots of the online data portals used by the workshop.

Saves PNGs into ``docs/workshop/images/`` that are embedded by
``docs/workshop/2.data.ipynb`` (generated by ``generate_workshop_series.py``).

Run from the repo root:

    .venv/bin/python scripts/capture_portal_screenshots.py [--out docs/workshop/images]

Requires Playwright + Chromium:
    pip install playwright && playwright install chromium

The script is defensive: a portal that times out or blocks headless rendering
is reported and skipped rather than aborting the whole run.
"""

from __future__ import annotations

import argparse
import contextlib
from pathlib import Path

from playwright.sync_api import sync_playwright

VIEWPORT = {"width": 1440, "height": 900}

# url, filename, description, css selector to wait for (optional), post action (optional)
#   action "pretty_xml": re-render the raw XML body as a styled <pre>
PORTALS = [
    (
        "https://www.gebco.net/data-products/gridded-bathymetry-data/",
        "portal-gebco.png",
        "GEBCO grid download page (global grids)",
        None,
    ),
    (
        "https://download.gebco.net/",
        "portal-gebco-subset.png",
        "GEBCO subsetting app",
        None,
    ),
    (
        "https://data.ceda.ac.uk/bodc/gebco/global/gebco_2026/ice_surface_elevation/netcdf/",
        "portal-gebco-ceda.png",
        "GEBCO 2026 global NetCDF on NERC CEDA",
        None,
    ),
    (
        "https://data.source.coop/giswqs/gebco-bathymetry/",
        "portal-gebco-cog.png",
        "GEBCO 2026 cloud-optimised GeoTIFF (source.coop)",
        None,
        "pretty_xml",
    ),
    (
        "https://www.geoboundaries.org/",
        "portal-geoboundaries.png",
        "GeoBoundaries admin boundaries",
        None,
    ),
    (
        "https://gadm.org/",
        "portal-gadm.png",
        "GADM global admin areas",
        None,
    ),
    (
        "https://download.geofabrik.de/asia/philippines.html",
        "portal-geofabrik.png",
        "Geofabrik OSM extract for the Philippines",
        None,
    ),
    (
        "https://earth.gsfc.nasa.gov/geo/data/ocean-tide-models",
        "portal-nasa-got.png",
        "NASA GSFC ocean tide models (GOT4.10c)",
        None,
    ),
    (
        "https://www.aviso.altimetry.fr/en/data/products/auxiliary-products/global-tide-fes.html",
        "portal-aviso-fes.png",
        "AVISO FES2014 tidal solution",
        None,
    ),
    (
        "https://www.tpxo.net/global/tpxo9-atlas",
        "portal-tpxo.png",
        "TPXO9-atlas tidal solution",
        None,
    ),
    (
        "https://pytmd.readthedocs.io/en/stable/",
        "portal-pytmd.png",
        "pyTMD Python tide model access library",
        None,
    ),
    (
        "https://emodnet.ec.europa.eu/en/bathymetry",
        "portal-emodnet.png",
        "EMODnet Bathymetry portal",
        None,
    ),
]

# selectors commonly used for cookie/consent banners, tried in order
ACCEPT_SELECTORS = [
    "button:has-text('Accept')",
    "button:has-text('Accept all')",
    "button:has-text('AGREE')",
    "button:has-text('I agree')",
    "button:has-text('Got it')",
    "button:has-text('OK')",
    "#accept-cookies",
    ".accept-cookies",
    "button#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll",
]


def _xml_listing_rows(raw: str) -> list[tuple[str, str]]:
    """Parse an S3 bucket-listing XML into (key, human-size) rows."""
    import re

    keys = re.findall(r"<Key>(.*?)</Key>", raw, flags=re.S)
    sizes = re.findall(r"<Size>(\d+)</Size>", raw, flags=re.S)
    rows = []
    for i, key in enumerate(keys):
        size = int(sizes[i]) if i < len(sizes) else 0
        rows.append((key, _human_size(size)))
    return rows


def _human_size(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < 1024 or unit == "TB":
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024
    return f"{n:.1f} TB"


def dismiss_consent(page) -> None:
    """Best-effort dismissal of cookie/consent banners."""
    for selector in ACCEPT_SELECTORS:
        try:
            btn = page.locator(selector).first
            if btn.is_visible(timeout=1200):
                btn.click(timeout=2000)
                page.wait_for_timeout(600)
                return
        except Exception:
            continue


def capture(
    url: str, out: Path, wait_selector: str | None, action: str | None = None
) -> bool:
    with sync_playwright() as pw:
        browser = pw.chromium.launch()
        page = browser.new_page(viewport=VIEWPORT, device_scale_factor=1)
        try:
            page.goto(url, wait_until="load", timeout=60000)
        except Exception as exc:
            print(f"  !! goto failed for {url}: {exc}")
            browser.close()
            return False

        dismiss_consent(page)

        with contextlib.suppress(Exception):
            page.wait_for_load_state("networkidle", timeout=30000)

        if wait_selector:
            with contextlib.suppress(Exception):
                page.locator(wait_selector).first.wait_for(
                    state="visible", timeout=20000
                )

        if action == "pretty_xml":
            import urllib.request

            try:
                req = urllib.request.Request(
                    url,
                    headers={
                        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
                    },
                )
                with urllib.request.urlopen(req, timeout=30) as r:
                    raw = r.read().decode("utf-8", "replace")
            except Exception as exc:
                print(f"  !! could not fetch listing for {url}: {exc}")
                browser.close()
                return False
            rows = _xml_listing_rows(raw)
            import html as _html

            trs = "".join(
                f"<tr><td>{_html.escape(k)}</td><td class='sz'>{_html.escape(s)}</td></tr>"
                for k, s in rows
            )
            doc = (
                "<!doctype html><html><head><meta charset='utf-8'>"
                "<style>body{font-family:Menlo,Consolas,monospace;font-size:13px;"
                "background:#f6f8fa;color:#24292f;margin:0;padding:24px;}"
                "h1{font-size:16px;color:#0b3d52;}ul{list-style:none;padding:0;}"
                "li{padding:4px 0;border-bottom:1px solid #e1e4e8;}"
                "a{color:#0969da;text-decoration:none;}"
                ".sz{color:#57606a;float:right;}</style></head><body>"
                "<h1>data.source.coop / giswqs/gebco-bathymetry/</h1><table>"
                + trs
                + "</table></body></html>"
            )
            import tempfile

            tmp = Path(tempfile.mktemp(suffix=".html"))
            tmp.write_text(doc)
            try:
                page.goto(tmp.as_uri(), wait_until="load", timeout=20000)
            finally:
                tmp.unlink(missing_ok=True)
            page.wait_for_timeout(400)

        page.evaluate("() => window.scrollTo(0, 0)")
        page.wait_for_timeout(1200)
        page.screenshot(path=str(out))
        browser.close()
        return True


def main() -> None:
    parser = argparse.ArgumentParser(description="Capture data-portal screenshots")
    parser.add_argument(
        "--out",
        default=str(
            Path(__file__).resolve().parent.parent / "docs" / "workshop" / "images"
        ),
        help="output directory (default: docs/workshop/images)",
    )
    parser.add_argument("--only", nargs="*", default=None, help="only these filenames")
    args = parser.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    ok = skipped = 0
    for url, fname, label, sel, *rest in PORTALS:
        action = rest[0] if rest else None
        if args.only and fname not in args.only:
            continue
        out = out_dir / fname
        print(f"== {label}\n   {url}")
        if out.exists():
            print(f"   -> exists, skipping ({out})")
            skipped += 1
            continue
        if capture(url, out, sel, action):
            ok += 1
            print(f"   -> saved {out}")
        else:
            print(f"   -> FAILED {fname}")
        print()

    print(f"Done: {ok} captured, {skipped} skipped (already present).")
    print("Files are in", out_dir)


if __name__ == "__main__":
    main()
